#!/usr/bin/env python3

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.

def fibo(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibo(n - 1) + fibo(n - 2)


def main():
    print("Problem 2")
    MAX_VALUE = 4000000
    f = fibo(0)
    cumulative = 0
    cumulative += f if (f % 2 == 0) else 0
    i = 1
    while f <= MAX_VALUE:
        f = fibo(i)
        cumulative += f if (f % 2 == 0) else 0
        i += 1

    print(cumulative)


main()
